#ifndef SOLVER_ACTION_H
#define SOLVER_ACTION_H

typedef enum {
    ACT_NONE = 40,
    SET_MOUSE_INFO,
    SET_VISITED,
    SET_WALL,
    READ_WALL,
    // 基本移動（今のmacroと一致）
    ACT_MOVE_1CELL,
    ACT_TURN_LEFT_MOVE,
    ACT_TURN_RIGHT_MOVE,
    ACT_TURN_BACK,
    ACT_MOVE_HALF_CELL,

    ACT_MOVE_FIRST_HALF_CELL,

    ACT_S45_LEFT,
    ACT_S45_RIGHT,
    ACT_S90_LEFT,
    ACT_S90_RIGHT,
    ACT_S180_LEFT,
    ACT_S180_RIGHT,
    ACT_S135_LEFT,
    ACT_S135_RIGHT,
    ACT_V90_LEFT,
    ACT_V90_RIGHT,

    ACT_FINISH,
    ACT_ERROR
} Action;

#endif /* SOLVER_ACTION_H */